### ISSUE TITLE
Add creation options for driver output

### ISSUE THREAD

**Issue by asartonev** [caliskanmurat/qgis_raster_divider_plugin#1]
I think adding creation options to the plugin output would be quite useful. For instance I need to be able to set compression options to my GeoTIFF files and output TFW files.

I have implemented a simple design that looks like this:
![creation_options_example](https://user-images.githubusercontent.com/2813233/194573567-3d282cfc-1645-4db0-a2a9-a640eb4ed222.png)

I can create a pull request with my changes if you feel it is appropriate?

EDIT: I am not sure if it comes across clearly in my comment - this is a working implementation, not just the UI design.

**Comment by vincedchart** [comment]
I really like this plugin, but I need a compression level to output files too (lzw, deflate..)

As I'm currently dealing with a 140,000 px or so, lzw tif file, that I need to cut into pieces of 1000 pixels : i'm unable to do this because of the 4MB size of each file and I guess there will be dozens of thousands of them

I'm currently using the following, to compress afterwards (maybe use compress=deflate too)

_**mkdir done; for f in *.tif; do gdal_translate -co COMPRESS=LZW "$f" done/"$f"; done;**_

but now, the amount of data looks too big to handle.

**Comment by caliskanmurat** [comment]
Hello vincedchart and asartonev,
Thank you for your contribuions.
I updated and uploaded the plugin. After approval it can be used.
