### ISSUE TITLE
Overlapping Rasters

### ISSUE THREAD

**Issue by johanferguson** [caliskanmurat/qgis_raster_divider_plugin#4]
Hi.

I am getting a problem of the rasters that divided overlapping each other. 
Is there a way to prohibit the rasters overlapping each other?

**Comment by caliskanmurat** [comment]
Hi,
Unfortunately overlap is an obligation sometimes. For example; assume that you have a raster with size of 1000x1000 pixels and you want to split it into subrasters with size of 150x150 pixels. After split, you get subrasters (150px) and also residual (100px). In order to avoid this, overlaps are inevitable.
I hope I could make it clear for you.

Thanks for your interest by the way.
